import Head from "next/head";
import ContactForm from "../components/ContactForm";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

const contact = () => {
  return (
    <div>
      <Head>
        <title>Sofie Herter | Contact Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <ContactForm />
      <Footer />
    </div>
  );
};
export default contact;
