import Head from "next/head";
import Navbar from "../components/Navbar";
import Gallery from "../components/Gallery";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sofie Herter | Photography</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Gallery />
    </div>
  );
}
